# Generated by Django 4.2.17 on 2024-12-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pipmart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="items",
        ),
        migrations.AddField(
            model_name="item",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="pipmart.purchase",
            ),
        ),
    ]
