import sampleImage1 from "@assets/sample_product_1.jpg";
import sampleImage2 from "@assets/sample_product_2.jpg";
import sampleImage3 from "@assets/sample_product_3.jpg";
import sampleImage4 from "@assets/sample_product_4.jpg";

export const users = [
    {
        id: 1,
        name: 'John Doe',
        username: 'johndoe',
        password: 'password123',
        email: 'johndoe@example.com',
    },
    {
        id: 2,
        name: 'Jane Smith',
        username: 'janesmith',
        password: 'mypassword456',
        email: 'janesmith@example.com',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        username: 'alicejohnson',
        password: 'securepassword789',
        email: 'alicejohnson@example.com',
    },
]

export const sampleProducts = [
    {
        id: 1,
        image: sampleImage1,
        title: 'Product 1',
        price: 120.0,
        isOnSale: true,
        salePrice: 99.99,
    },
    {
        id: 2,
        image: sampleImage2,
        title: 'Product 2',
        price: 75.0,
        isOnSale: false,
        salePrice: null,
    },
    {
        id: 3,
        image: sampleImage3,
        title: 'Product 3',
        price: 50.0,
        isOnSale: true,
        salePrice: 40.0,
    },
    {
        id: 4,
        image: sampleImage4,
        title: 'Product 4',
        price: 200.0,
        isOnSale: false,
        salePrice: null,
    },
    {
        id: 5,
        image: sampleImage1,
        title: 'Product 5',
        price: 89.99,
        isOnSale: false,
    },
    {
        id: 6,
        image: sampleImage2,
        title: 'Product 6',
        price: 110.0,
        isOnSale: true,
        salePrice: 95.0,
    },
    {
        id: 7,
        image: sampleImage3,
        title: 'Product 7',
        price: 150.0,
        isOnSale: false,
    },
    {
        id: 8,
        image: sampleImage4,
        title: 'Product 8',
        price: 45.0,
        isOnSale: true,
        salePrice: 30.0,
    },
    {
        id: 9,
        image: sampleImage1,
        title: 'Product 9',
        price: 250.0,
        isOnSale: true,
        salePrice: 200.0,
    },
    {
        id: 10,
        image: sampleImage2,
        title: 'Product 10',
        price: 60.0,
        isOnSale: false,
    },
    {
        id: 11,
        image: sampleImage3,
        title: 'Product 11',
        price: 99.99,
        isOnSale: true,
        salePrice: 79.99,
    },
    {
        id: 12,
        image: sampleImage4,
        title: 'Product 12',
        price: 130.0,
        isOnSale: false,
    },
];

export const detailedProducts = [
    {
        id: 1,
        image: sampleImage1,
        title: 'Product 1',
        description: 'A versatile and stylish item perfect for daily use.',
        price: 120.0,
        isOnSale: true,
        salePrice: 99.99,
        dateAdded: '2024-01-01',
    },
    {
        id: 2,
        image: sampleImage2,
        title: 'Product 2',
        description: 'A durable product with premium quality materials.',
        price: 75.0,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-01-05',
    },
    {
        id: 3,
        image: sampleImage3,
        title: 'Product 3',
        description: 'Compact and lightweight, ideal for travelers.',
        price: 50.0,
        isOnSale: true,
        salePrice: 40.0,
        dateAdded: '2024-01-10',
    },
    {
        id: 4,
        image: sampleImage4,
        title: 'Product 4',
        description: 'Luxury product crafted for elegance and performance.',
        price: 200.0,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-01-12',
    },
    {
        id: 5,
        image: sampleImage1,
        title: 'Product 5',
        description: 'An affordable option with exceptional value.',
        price: 89.99,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-01-15',
    },
    {
        id: 6,
        image: sampleImage2,
        title: 'Product 6',
        description: 'High-quality item perfect for modern needs.',
        price: 110.0,
        isOnSale: true,
        salePrice: 95.0,
        dateAdded: '2024-01-18',
    },
    {
        id: 7,
        image: sampleImage3,
        title: 'Product 7',
        description: 'Premium build and outstanding performance.',
        price: 150.0,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-01-20',
    },
    {
        id: 8,
        image: sampleImage4,
        title: 'Product 8',
        description: 'Lightweight and easy to carry, ideal for quick tasks.',
        price: 45.0,
        isOnSale: true,
        salePrice: 30.0,
        dateAdded: '2024-01-22',
    },
    {
        id: 9,
        image: sampleImage1,
        title: 'Product 9',
        description: 'A top-tier product offering unmatched quality.',
        price: 250.0,
        isOnSale: true,
        salePrice: 200.0,
        dateAdded: '2024-01-25',
    },
    {
        id: 10,
        image: sampleImage2,
        title: 'Product 10',
        description: 'A simple and reliable choice for daily needs.',
        price: 60.0,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-01-28',
    },
    {
        id: 11,
        image: sampleImage3,
        title: 'Product 11',
        description: 'An innovative product designed for efficiency.',
        price: 99.99,
        isOnSale: true,
        salePrice: 79.99,
        dateAdded: '2024-02-01',
    },
    {
        id: 12,
        image: sampleImage4,
        title: 'Product 12',
        description: 'Engineered for long-lasting performance.',
        price: 130.0,
        isOnSale: false,
        salePrice: null,
        dateAdded: '2024-02-05',
    },
];

